services:
  - type: web
    name: jitted-web
    env: node
    plan: free
    region: frankfurt
    rootDir: web
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.10.0
      - key: DATABASE_URL
        fromDatabase:
          name: jitted-db
          property: connectionString
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        sync: false

databases:
  - name: jitted-db
    plan: free
    databaseName: jitted
    user: jitted_user
